// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0EPbBe143O44Usbc2b9gyWLBqo1laPrA',
    appId: '1:223069081183:web:560b36ea710ee51d64d5ea',
    messagingSenderId: '223069081183',
    projectId: 'jahitbajuapps',
    authDomain: 'jahitbajuapps.firebaseapp.com',
    storageBucket: 'jahitbajuapps.appspot.com',
    measurementId: 'G-0E5S8Y064Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3-t-oD0XY8yASu3MdRHP_hhjg7a-xgCM',
    appId: '1:223069081183:android:787f16140c9a5d5564d5ea',
    messagingSenderId: '223069081183',
    projectId: 'jahitbajuapps',
    storageBucket: 'jahitbajuapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmq_tHTo6xZG3CSiV46geiRswCWSA7Wp0',
    appId: '1:223069081183:ios:334f6cfb47f316af64d5ea',
    messagingSenderId: '223069081183',
    projectId: 'jahitbajuapps',
    storageBucket: 'jahitbajuapps.appspot.com',
    iosClientId: '223069081183-qbss8ueqvi8a905q0mqihdb7ut2p9aet.apps.googleusercontent.com',
    iosBundleId: 'com.example.jahitBaju',
  );
}
